name: Web Starter Kit
pygments: true
baseurl: /web-starter
exclude: [vendor/]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
